# -*- coding: utf-8 -*-
"""Log_Analyzer.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1je-q73ZVvEY8T6rSi5bF7Bp9cIYQkaYq
"""

print("**Make sure individual Logs are immediately Seperated by comma (,) only.")
Logs = input("Enter Logs: ")

# Returns log elements in the form of list
def getLogLines(Logs):
  return Logs.split(',')

# # Creates a log file from user input and returns it
def getLogFile(Logs):
  with open('LogFile.txt', 'w') as SampleLog:
    LogLines = getLogLines(Logs)
    for line in LogLines:
      SampleLog.write(line+'\n')
  return open('LogFile.txt')

# Analyses the log entered for its log type, frequency and prints the analysis
def LogAnalyzer(Logs):
  lnum = 0
  LogFile = getLogFile(Logs)
  count = {"INFO":0 , "WARNING":0 , "ERROR":0 , "DEBUG":0 , "CRITICAL":0}
  while True:
    Line = LogFile.readline()
    if not Line:
      break
    lnum += 1
    # To Extract the first word of each log line
    firstWord = Line[0:(Line.find(" "))]
    count[firstWord] += 1
  print("Total logs: ",lnum)
  for k,v in count.items():
      print(f"{k} : {v}")

print("Log Analysis:\n")
LogAnalyzer(Logs)

Line = input("Enter Log:")
firstWord = Line[0:(Line.find(" "))]
count = {"INFO":0 , "WARNING":0 , "ERROR":0}
count[firstWord] += 1
print(firstWord)

