# -*- coding: utf-8 -*-
"""Password_Checker.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jWF99rdB4QpR3quLK91av1-Cz5d6sAEu
"""

## Checks if the 'password' is valid.
def isValid(password):
  if 8<=len(password)<=15:
    pass_st = "0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ!@#_-$"
    for ch in password:
      if pass_st.find(ch)==-1:
        print(f"Your Password should be comprised of the given characters only: {pass_st}")
        return ""
    return "Valid"
  else:
    print("WARNING: Your Password length should between 8 to 15 characters.")
    return ""

## Checks if there is atleast one Number in the 'password'.
def hasNumber(password):
    c=0
    Num="0123456789"
    for i in password:
      if Num.find(i) != -1:
        c+=1
    if c != 0:
      return True
    else:
      return False

## Checks if there is atleast one Upper Case letter in the 'password'.
def hasUpperCase(password):
    c=0
    up="ABCDEFGHIJKLMNOPQRSTUVWXYZ"
    for i in password:
      if up.find(i) != -1:
        c+=1
    if c != 0:
      return True
    else:
      return False

## Checks if there is atleast one Lower Case letter in the 'password'.
def hasLowerCase(password):
    c=0
    lo="abcdefghijklmnopqrstuvwxyz"
    for i in password:
      if lo.find(i) != -1:
        c+=1
    if c != 0:
      return True
    else:
      return False

## Checks if there is atleast one (Allowed) Special Character in the 'password'.
def hasSpecialChar(password):
    c=0
    sp="!@#$_-"
    for i in password:
      if sp.find(i) != -1:
        c+=1
    if c != 0:
      return True
    else:
      return False

## Primary Functions that evaluates the strength of 'password'.
def strength_check(password):
  if isValid(password) == "Valid":
    if hasNumber(password) and hasLowerCase(password) and hasUpperCase(password) and hasSpecialChar(password):
      print("Password Strength: Strong")
    elif hasNumber(password) and hasLowerCase(password) and hasUpperCase(password):
      print("Password Strength: Medium")
    else:
      print("Password Strength: Weak")
      print("We Suggest Changing your Password.")


print("This Snippet Checks your Password Strength.")
print("Please enter the password you want to check.")
print("WARNING: Your Password length should between 8 to 15 characters.")
strength_check(input("Enter Your Password: "))

